<?php
print "Hello, World! php version is " . PHP_VERSION . "\n";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air"; 
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
print "a change in the air";
?>
